### ISSUE TITLE
JOSS Review - comments on paper

### ISSUE THREAD

**Issue by speth** [uw-comphys/openccm#43]
I appreciate the opportunity to review this tool for JOSS (https://github.com/openjournals/joss-reviews/issues/6963). OpenCCM seems like it could be a useful tool in a number of different areas. Besides the other issues I opened regarding the software, I wanted to offer some comments / suggestions for the paper itself:

- Summary, L20: OpenFOAM reference is undated, but the linked doc does have a date that could be used
- The in-text reference to AMBER is awkward, appearing as "(Compartment Modelling Software, n.d.)" -- my suggestion would be to list the name of the company as the "Author".
- In the "Features" table:
  - It is a bit hard to tell what "Description" lines go with what "Feature", especially the line "Previous SotA CSTR-based models". I'm not sure how easy this is to improve in a Markdown table, though.
  - The acronyms PFR, CSTR here are not expanded even though this is the first time they are used
  - "state of the art" should just be written out.
- In the description of the user interface, the input file is described as "text based," but is there any more structure to it than that? An example would aid in understanding.
- L78: "specie" should be "species"
- L82/L117: The chemical equation is poorly formatted -- elements should not be italicized, and the subscripts should be subscripts.
- L118: What are the units of the rate constants specified here. And later, the units of concentration?

**Comment by Alex-Vasile** [comment]
> In the description of the user interface, the input file is described as "text based," but is there any more structure to it than that? An example would aid in understanding.

The main directory contains two example config files, `CONFIG` and `CONFIG_REACTIONS`. Would indicating their existence and pointing the reader to it address this comment?

**Comment by speth** [comment]
> The main directory contains two example config files, `CONFIG` and `CONFIG_REACTIONS`. Would indicating their existence and pointing the reader to it address this comment?

Does the `CONFIG` file in the repository root describe all of the available configuration options? If so, then I would say yes, pointing to these files is sufficient. Repeating this information in the documentation website would also help clarify how to use the software.

**Comment by speth** [comment]
Something else I noticed while looking at the reactions config file for the `pipe_with_recirc_2d` example is that it uses species names like `Na2CO3`, while the the "Reaction Configuration File" section of the paper suggests that only letters are allowed in species names, requiring these species names to be replaced with abstract ones like `a` or `b`. Is this a recent change to the code to support a more natural naming convention?

**Comment by Alex-Vasile** [comment]
There was a recent code change to improve that, the manuscript was update to reflect it, but a new version has not been generated. It doesn't look like the bot will respond to me in the original issue.

**Comment by speth** [comment]
Thank you, I think all of my original comments have been addressed. I have just two more small items based on looking at the revised manuscript:

- The sample section of the input file (lines 74-84) runs off the right side of the page, so I suppose you need to manually wrap the comments for the sake of the manuscript.
- I'm not sure what is meant by lines 149-150, "Input/Output Concentrations for ‘NaCl’." etc.

**Comment by Alex-Vasile** [comment]
> Thank you, I think all of my original comments have been addressed. I have just two more small items based on looking at the revised manuscript:
> 
> * The sample section of the input file (lines 74-84) runs off the right side of the page, so I suppose you need to manually wrap the comments for the sake of the manuscript.
> * I'm not sure what is meant by lines 149-150, "Input/Output Concentrations for ‘NaCl’." etc.

I've added done the word wrap manually. The "Input/Output concentrations" is Alt text for the figures that should have been there. That was an oversight on my part; when I update the specie names from `a`, `b`, etc. to `NaCl` and the like I forgot to change the file names referenced in the manuscript to reflected those changes.

**Comment by Alex-Vasile** [comment]
@speth Has everything in this issue been addressed?

**Comment by speth** [comment]
Yes, I believe so.
